#!/bin/bash
#Script created by Bosun Dare. 



echo "Enter full path name of vlan file"
read vlan_file
if [ ! -f "$vlan_file" ]; then
    echo "No such file!" >&2
    exit 1
fi
echo "Enter Full path name of Network Address File"
read ip_file
if [ ! -f "$ip_file" ]; then
    echo "No such file!" >&2
    exit 1
fi


vlan_line=$( wc -l <"$vlan_file" )
ip_line=$( wc -l <"$ip_file" )

if [ $ip_line != $vlan_line ]; then 
echo "Ensure both files have the same line number" >&2
    exit 1
fi
working_dir=$HOME/$RANDOM.script
mkdir $working_dir

echo "This script would create a folder located in $HOME with full path $working_dir"
echo "creating files"

touch $working_dir/switchconfigs1 
touch $working_dir/switchconfigs2

echo "Now writing configs to $working_dir/switchconfigs1 and $working_dir/switchconfigs2. You can tail the output to monitor with tail -f $working_dir/switchconfigs1"
cp $vlan_file $working_dir/vlan.in
cp $ip_file $working_dir/ip.in


for (( i=1; i<=$vlan_line; i++ )) 
do

one=`head -1 $working_dir/ip.in`
two=`head -1 $working_dir/vlan.in`

# Splits IP address 
oct1=`echo $one | awk -F. '{print $1}'`
oct2=`echo $one | awk -F. '{print $2}'`
oct3=`echo $one | awk -F. '{print $3}'`
oct4=`echo $one | awk -F. '{print $4}'`

#uses last octect of IP to determine IP services.
usestart4=`expr $oct4 + 1`
uselast4=`expr $oct4 + 30`
lastuse=$oct1.$oct2.$oct3.$uselast4
routerip=`expr $oct4 + 1`
routerip=$oct1.$oct2.$oct3.$routerip
vlanip1=`expr $oct4 + 2`
vlanipsw1=$oct1.$oct2.$oct3.$vlanip1
firstuseoct=`expr $oct4 + 5`
firstuse=$oct1.$oct2.$oct3.$firstuseoct
vlanip2=`expr $oct4 + 3`
vlanipsw2=$oct1.$oct2.$oct3.$vlanip2


# Writing to switch
echo "interface vlan $two" >> $working_dir/switchconfigs1 
echo "desc GTS_VLANS_2020"  >> $working_dir/switchconfigs1
echo "ip address $vlanipsw1/27" >> $working_dir/switchconfigs1
echo "ip virtual-router address $routerip" >> $working_dir/switchconfigs1
echo "###########################" >> $working_dir/switchconfigs1

echo "interface vlan $two" >> $working_dir/switchconfigs2
echo "desc GTS_VLANS_2020"  >> $working_dir/switchconfigs2
echo "ip address $vlanipsw2/27" >> $working_dir/switchconfigs2
echo "ip virtual-router address $routerip" >> $working_dir/switchconfigs2
echo "###########################" >> $working_dir/switchconfigs2

echo "VLAN $two	Usable IP $firstuse - $lastuse	Gateway $routerip Subnet Mask 255.255.255.224" >> $working_dir/info 
echo $two >> $working_dir/vlan.out
echo $routerip >> $working_dir/router.out
echo $firstuse >> $working_dir/firstuse.out
echo $lastuse >> $working_dir/lastuse.out

echo $one >> $working_dir/ip.in
echo $two >> $working_dir/vlan.in
sed -i -e "1d" $working_dir/vlan.in
sed -i -e "1d" $working_dir/ip.in
done
echo "Script has completed. View Switch Configs at $working_dir/switchconfigs1 and $working_dir/switchconfigs2"
rm -rf $working_dir/vlan.in $working_dir/ip.in

